"""Synthetic demo data.

Everything here is generated: the projects are invented, the traffic is random,
and the "API keys" are locally generated strings that are not valid anywhere.
The point is to let someone clone this repo and see a populated dashboard in
one command without ever touching a real credential.
"""

from __future__ import annotations

import random
from datetime import datetime, timedelta, timezone

from sqlalchemy import select
from sqlalchemy.orm import Session

from . import crypto
from .app import sync_builtin_providers
from .db import init_db, session_scope
from .models import Credential, Project, Provider, RequestEvent, UseCase, VirtualKey

DEMO_PROJECTS = [
    ("recipe-app", "Recipe App", 25.0),
    ("client-dashboard", "Client Dashboard", 150.0),
    ("newsletter-bot", "Newsletter Bot", 10.0),
    ("market-research", "Market Research", None),
]

DEMO_USE_CASES = [
    ("llm-summary", "LLM Summary"),
    ("chat", "Chat"),
    ("embeddings", "Embeddings"),
    ("web-scraping", "Web Scraping"),
    ("search", "Search"),
    ("classification", "Classification"),
]

# (provider, model, use_case, avg input tokens, avg output tokens, weight)
DEMO_MIX = [
    ("openrouter", "anthropic/claude-sonnet-4", "chat", 2400, 700, 18),
    ("openrouter", "openai/gpt-4o-mini", "llm-summary", 3800, 420, 30),
    ("openrouter", "deepseek/deepseek-chat", "classification", 900, 120, 14),
    ("openai", "gpt-4o", "chat", 1800, 600, 10),
    ("openai", "text-embedding-3-small", "embeddings", 640, 0, 16),
    # No rate in the catalog on purpose: this is what "unpriced spend" looks like.
    ("openrouter", "some-lab/experimental-v2", "llm-summary", 1500, 500, 4),
    ("firecrawl", "", "web-scraping", 0, 0, 12),
    ("serper", "", "search", 0, 0, 9),
]

DEMO_CREDENTIALS = [
    ("openrouter", "openrouter-personal", "recipe-app"),
    ("openrouter", "openrouter-client-work", "client-dashboard"),
    ("openrouter", "openrouter-shared", None),
    ("openai", "openai-main", None),
    ("firecrawl", "firecrawl-scraping", None),
    ("serper", "serper-search", None),
    ("tavily", "tavily-unused", None),  # never called: shows up as an idle key
]


def _fake_key(prefix: str) -> str:
    """A locally generated stand-in. Not a credential for anything."""
    import secrets

    return f"{prefix}-demo-{secrets.token_hex(16)}"


def seed_demo(events: int = 4000, days: int = 45, seed: int = 7) -> dict[str, int]:
    """Populate the database with a realistic-looking month and a half of traffic."""
    rng = random.Random(seed)
    init_db()
    sync_builtin_providers()

    with session_scope() as session:
        projects = _ensure_projects(session)
        use_cases = _ensure_use_cases(session)
        credentials = _ensure_credentials(session, projects)
        _ensure_virtual_keys(session, projects, use_cases)
        created = _generate_events(session, rng, projects, use_cases, credentials, events, days)

    return {"events": created, "projects": len(DEMO_PROJECTS), "credentials": len(DEMO_CREDENTIALS)}


def _ensure_projects(session: Session) -> dict[str, Project]:
    out = {}
    for slug, name, budget in DEMO_PROJECTS:
        project = session.scalar(select(Project).where(Project.slug == slug))
        if project is None:
            project = Project(
                slug=slug,
                name=name,
                monthly_budget_usd=budget,
                description="Demo project generated by `openmetric demo`.",
            )
            session.add(project)
            session.flush()
        out[slug] = project
    return out


def _ensure_use_cases(session: Session) -> dict[str, UseCase]:
    out = {}
    for slug, name in DEMO_USE_CASES:
        use_case = session.scalar(select(UseCase).where(UseCase.slug == slug))
        if use_case is None:
            use_case = UseCase(slug=slug, name=name)
            session.add(use_case)
            session.flush()
        out[slug] = use_case
    return out


def _ensure_credentials(session: Session, projects: dict[str, Project]) -> dict[str, Credential]:
    out: dict[str, Credential] = {}
    for provider_slug, label, project_slug in DEMO_CREDENTIALS:
        provider = session.scalar(select(Provider).where(Provider.slug == provider_slug))
        if provider is None:
            continue
        credential = session.scalar(select(Credential).where(Credential.label == label))
        if credential is None:
            secret = _fake_key(provider_slug)
            credential = Credential(
                provider_id=provider.id,
                project_id=projects[project_slug].id if project_slug else None,
                label=label,
                encrypted_secret=crypto.encrypt(secret),
                key_hint=crypto.hint(secret),
                key_fingerprint=crypto.fingerprint(secret),
                notes="Demo credential - not a real key.",
            )
            session.add(credential)
            session.flush()
        out[label] = credential
    return out


def _ensure_virtual_keys(
    session: Session, projects: dict[str, Project], use_cases: dict[str, UseCase]
) -> None:
    for slug, project in projects.items():
        name = f"{slug}-key"
        if session.scalar(select(VirtualKey).where(VirtualKey.name == name)):
            continue
        token = crypto.new_virtual_key("test")
        session.add(
            VirtualKey(
                name=name,
                token_hash=crypto.hash_virtual_key(token),
                token_hint=f"...{token[-6:]}",
                project_id=project.id,
            )
        )


def _generate_events(
    session: Session,
    rng: random.Random,
    projects: dict[str, Project],
    use_cases: dict[str, UseCase],
    credentials: dict[str, Credential],
    count: int,
    days: int,
) -> int:
    from . import pricing

    now = datetime.now(timezone.utc)
    provider_ids = {
        p.slug: p for p in session.scalars(select(Provider)) if p.slug in {m[0] for m in DEMO_MIX}
    }
    weights = [m[5] for m in DEMO_MIX]
    project_slugs = list(projects)
    # Later projects ramp up over time, so the trend charts have something to show.
    project_weights = [5, 9, 3, 2]

    created = 0
    for _ in range(count):
        mix = rng.choices(DEMO_MIX, weights=weights, k=1)[0]
        provider_slug, model, use_case_slug, avg_in, avg_out, _ = mix
        provider = provider_ids.get(provider_slug)
        if provider is None:
            continue

        age_days = rng.triangular(0, days, days * 0.35)
        created_at = now - timedelta(days=age_days, minutes=rng.randint(0, 1440))

        project_slug = rng.choices(project_slugs, weights=project_weights, k=1)[0]
        project = projects[project_slug]
        # ~6% of traffic is deliberately untagged, to exercise the blindspot check.
        untagged = rng.random() < 0.06

        credential = _pick_credential(rng, credentials, provider_slug, project_slug)
        input_tokens = max(int(rng.gauss(avg_in, avg_in * 0.35)), 0) if avg_in else 0
        output_tokens = max(int(rng.gauss(avg_out, avg_out * 0.5)), 0) if avg_out else 0

        failed = rng.random() < 0.035
        status = rng.choice([429, 500, 401, 400]) if failed else 200
        if failed:
            output_tokens = 0

        if input_tokens or output_tokens:
            cost, source = pricing.price_tokens(model, input_tokens, output_tokens)
            units, unit_kind = 0.0, ""
        else:
            units = float(rng.randint(1, 10))
            cost, source, unit_kind = pricing.price_units(provider_slug, units)

        latency = int(rng.gauss(900, 350)) if provider.kind == "llm" else int(rng.gauss(2200, 900))
        if rng.random() < 0.02:  # occasional slow tail
            latency *= rng.randint(4, 12)

        session.add(
            RequestEvent(
                created_at=created_at,
                project_id=None if untagged else project.id,
                use_case_id=None if untagged else use_cases[use_case_slug].id,
                provider_id=provider.id,
                credential_id=credential.id if credential else None,
                model=model,
                operation="chat"
                if model and output_tokens
                else ("embedding" if model else "scrape"),
                method="POST",
                path="/chat/completions" if model else "/v1/scrape",
                status_code=status,
                ok=not failed,
                error_type="" if not failed else f"http_{status}",
                latency_ms=max(latency, 40),
                streamed=bool(model) and rng.random() < 0.3,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                units=units,
                unit_kind=unit_kind,
                cost_usd=cost,
                cost_source=source,
                request_bytes=rng.randint(400, 9000),
                response_bytes=rng.randint(400, 40000),
            )
        )
        created += 1
        if created % 500 == 0:
            session.flush()

    # Reflect the generated traffic in each key's last-used stamp.
    for credential in credentials.values():
        last = session.scalar(
            select(RequestEvent.created_at)
            .where(RequestEvent.credential_id == credential.id)
            .order_by(RequestEvent.created_at.desc())
            .limit(1)
        )
        credential.last_used_at = last
    return created


def _pick_credential(
    rng: random.Random,
    credentials: dict[str, Credential],
    provider_slug: str,
    project_slug: str,
) -> Credential | None:
    candidates = {
        "openrouter": {
            "recipe-app": ["openrouter-personal", "openrouter-shared"],
            "client-dashboard": ["openrouter-client-work"],
            "newsletter-bot": ["openrouter-shared"],
            "market-research": ["openrouter-shared", "openrouter-personal"],
        },
        "openai": {"*": ["openai-main"]},
        "firecrawl": {"*": ["firecrawl-scraping"]},
        "serper": {"*": ["serper-search"]},
    }
    by_project = candidates.get(provider_slug, {})
    labels = by_project.get(project_slug) or by_project.get("*") or []
    labels = [label for label in labels if label in credentials]
    return credentials[rng.choice(labels)] if labels else None
